version: "3.9"
services:
  fastapi:
    image: python:3.8-bullseye
    container_name: fastapi
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - compose-bridge
    ports:
      - "80:80"
    volumes:
      - ./app:/code/app
    environment:
      - PORT=80
    command: uvicorn app.main:app --host 0.0.0.0 --port 80

  postgres:
    image: postgres:15.3-bullseye
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=abc123.
      - POSTGRES_DB=animals_db
    networks:
      - compose-bridge
    ports:
      - "5432:5432"

networks:
  compose-bridge:
    driver: bridge
